### ISSUE TITLE
Make a stream out of a string?

### ISSUE THREAD

**Issue by bcomnes** [jarofghosts/strum#3]
Would you be interested in making streams out of a string?

**Comment by jarofghosts** [comment]
i considered it, but what would that look like? stream one character at a time?

**Comment by bcomnes** [comment]
Mainly I was thinking for writing the string to a writeable stream for a file, in which case, 1 character at time isn't very practical.  Its mainly to make the string pipeable to a file.

**Comment by jarofghosts** [comment]
i guess i'm not sure the value of that over just `writeable.write(string)`, but there's no real harm (imo) in exposing it as an option. were you thinking of PRing it or is this more of a feature request?

**Comment by bcomnes** [comment]
I guess a feature request.  But nah, I don't think I'll really need it.
